#!/usr/bin/env bash
# 07 — Describe and suggest: auto-detect format, infer schema, get smart suggestions
set -euo pipefail
source "$(dirname "$0")/_helpers.sh"
setup_data

strip_ansi() { sed $'s/\033\[[0-9;]*m//g'; }

section "Describe: auto-detect format and schema"
echo "Feed fk any file — it detects format, headers, and column types:"
echo ""
printf "  ${C_DIM}\$ ${C_CYAN}${C_BOLD}fk${C_RESET} ${C_FLAG}--describe${C_RESET} ${C_FILE}orders.csv${C_RESET}\n\n"
$FK --describe "$TMPDIR/orders.csv"

echo ""
echo "Works on JSON too:"
echo ""
printf "  ${C_DIM}\$ ${C_CYAN}${C_BOLD}fk${C_RESET} ${C_FLAG}-d${C_RESET} ${C_FILE}api.jsonl${C_RESET}\n\n"
$FK -d "$TMPDIR/api.jsonl"

echo ""
echo "Or piped data (format and header inferred):"
echo ""
printf "  ${C_DIM}\$${C_RESET} ${C_YEL}df -h | ${C_CYAN}${C_BOLD}fk${C_RESET} ${C_FLAG}-d${C_RESET}\n\n"
printf "Filesystem      Size  Used  Avail  Use%%\n/dev/sda1       100G   45G    55G   45%%\n/dev/sdb1       500G  320G   180G   64%%\ntmpfs           8.0G  1.2G   6.8G   15%%\n" | $FK -d

section "Suggest: smart, tailored programs for your data"
echo "Don't know how to start? fk --suggest analyzes the data and tells you:"
echo ""
printf "  ${C_DIM}\$ ${C_CYAN}${C_BOLD}fk${C_RESET} ${C_FLAG}--suggest${C_RESET} ${C_FILE}orders.csv${C_RESET}\n\n"

# Capture suggest output — we'll display it AND extract the commands to run.
suggest_output=$($FK --suggest "$TMPDIR/orders.csv" 2>&1)
echo "$suggest_output"

section "Running every suggestion"
echo "Each command above was generated by --suggest. Let's run them all:"

# Extract the actual fk commands from the suggest output (strip ANSI, find lines starting with 'fk').
cmds=$(echo "$suggest_output" | strip_ansi | grep '^ *fk ' | sed 's/^ *//')

while IFS= read -r cmd; do
    # Display version: shorten temp paths for readability
    display="${cmd//$TMPDIR\//}"
    echo ""
    printf "  ${C_DIM}\$${C_RESET} ${C_CYAN}%s${C_RESET}\n" "$display"
    echo ""
    # Run version: replace leading 'fk' with full binary path
    runcmd="${FK}${cmd#fk}"
    eval "$runcmd" 2>&1 | while IFS= read -r line; do
        printf "    %s\n" "$line"
    done
done <<< "$cmds"

section "Suggest on different data shapes"
echo "Suggestions adapt to the data. Compare sales.csv (string+numeric columns):"
echo ""
$FK --suggest "$TMPDIR/sales.csv" 2>&1

echo ""
echo "vs. JSON Lines (api.jsonl):"
echo ""
$FK --suggest "$TMPDIR/api.jsonl" 2>&1

section "Compressed files"
echo "Compressed files are decompressed transparently (.gz, .zst, .bz2, .xz):"
echo ""
gzip -k "$TMPDIR/sales.csv"
printf "  ${C_DIM}\$ ${C_CYAN}${C_BOLD}fk${C_RESET} ${C_FLAG}-d${C_RESET} ${C_FILE}sales.csv.gz${C_RESET}\n\n"
$FK -d "$TMPDIR/sales.csv.gz"

echo ""
echo "No need for -i csv — fk infers it from the file extension:"
echo ""
show $FK -H '{ printf "  %-6s $%s\n", $region, $revenue }' "$TMPDIR/sales.csv.gz"

printf "\n${C_BOLD}Done.${C_RESET} --describe and --suggest turn unknown data into ready-to-run fk programs.\n"
